default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bitiment_development
  username: postgres
  password:

test:
  <<: *default
  database: bitiment_test
  username: postgres
  password:

production:
  <<: *default
  database: bitiment_production
  username: root
  password:
